mysite/bases/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'bases'
urlpatterns= [
    path("",views.landing, name='landing')
]

mysite/categories/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'categories'
urlpatterns= [
    #categories/1/
    path("<int:person_id>/<int:month>_<int:year>/",views.index, name='person_category_index'),
    #categories/1/newCategory/
    path("<int:person_id>/newCategory/",views.addCategory,name="new_category"),
    #categories/1/editCategory/2/
    path("<int:person_id>/editCategory/<int:category_id>/",views.editCategory,name="edit_category"),
    #categories/1/deleteCategory/2/
    path("<int:person_id>/deleteCategory/<int:category_id>/",views.deleteCategory,name='delete_category'),
    #categories/group/1/
    path("group/<int:group_id>/<int:month>_<int:year>/",views.index_team , name="team_category_index"),
    path("person/<int:person_id>/<int:month>_<int:year>/",views.index_person , name="person_category_index_summary"),

]

mysite/expenses/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'expenses'
urlpatterns= [
    #expenses/1/addExpense
    path("<int:person_id>/<int:category_id>/addExpense/",views.add_expense, name='add_expense'),
    path("<int:person_id>/<int:category_id>/detailExpense/",views.category_expense_list, name='category_expense_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('people/',include('people.urls')),
    path('categories/',include('categories.urls')),
    path('expenses/',include('expenses.urls')),
    path("",include('bases.urls'))

]

mysite/categories/models.py
from django.db import models
from people.models import People
from groups.models import Group
import datetime

# Create your models here.
class Category(models.Model):
    def __str__(self):
        return f"{self.category_person.person_name} {self.category_name} {self.category_date.month}/{self.category_date.year}"
    def calculate_left(self,expected,spent):
        return expected-spent 
    category_person = models.ForeignKey(People, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=200)
    category_expected = models.DecimalField(max_digits=8,decimal_places=2)
    category_spent = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    category_date = models.DateField(default=datetime.datetime.now)

mysite/categories/forms.py
from django import forms
from people.models import People
from .models import Category
from django.forms.widgets import HiddenInput

class CategoryAddForm(forms.ModelForm):

    class Meta:
        model= Category
        fields = [
            'category_person',
            'category_name',
            'category_expected',
            'category_spent',
            'category_date'
        ]
    
    def __init__(self,*args,**kwargs):
        hide_condition = kwargs.pop('hide_condition',None)
        super(CategoryAddForm, self).__init__(*args, **kwargs)
        if hide_condition:
            self.fields["category_person"].widget = HiddenInput()

mysite/categories/views.py
from django.shortcuts import render, redirect,get_object_or_404,get_list_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect

#MODELS
from groups.models import Group
from people.models import People
from .models import Category

#FORMS
from .forms import CategoryAddForm

import datetime
#==================Helper Functions#==================
def calculate_summary(categories):
    expected = 0
    spent = 0
    left = 0
    for category in categories:
        expected += category.category_expected
        spent += category.category_spent
    left = expected-spent
    return expected, spent, left

#==================Application level views#==================
def index(request,person_id,month,year):
    if request.user.is_authenticated:
        person = get_object_or_404(People, id=person_id)
        group = get_object_or_404(Group,id=person.group_couple.id)
        all_people = get_list_or_404(People,group_couple=group)
        if len(all_people) > 1:
            other_members = [ peep for peep in all_people if peep != person ]
        else:
            other_members = []
        if len(person.category_set.filter(category_date__month=month,category_date__year=year))>=1:
            categories= get_list_or_404(Category,category_person=person,category_date__month=month,category_date__year=year)
        else:
            categories = []
        expected,spent,left = calculate_summary(categories)
        today = datetime.datetime.today()
        current_user = get_object_or_404(People, username=request.user)
        context = {
            'person':person,
            'categories':categories,
            'month':today.month,
            'year':today.year,
            'other_members':other_members,
            'expected': expected,
            'spent': spent,
            'left':left,
            "current_user":current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request, "categories/index.html" ,context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

#==================Views here#==================
def index_team(request,group_id,month,year):
    if request.user.is_authenticated:
        group = get_object_or_404(Group,id=group_id)
        all_people = get_list_or_404(People,group_couple=group)
        categories = []
        for person in all_people:
            if len(person.category_set.filter(category_date__month=month,category_date__year=year))>0:
                categories.extend(get_list_or_404(Category,category_person=person,category_date__month=month,category_date__year=year))

        expected,spent,left = calculate_summary(categories)
        today = datetime.datetime.today()
        current_user = get_object_or_404(People, username=request.user)
        context = {
            'categories':categories,
            'month':today.month,
            'year':today.year,
            'expected': expected,
            'spent': spent,
            'left':left,
            "current_user":current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request, "categories/index_team.html" ,context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

def index_person(request,person_id,month,year):
    if request.user.is_authenticated:
        person = get_object_or_404(People,id=person_id)
        if len(person.category_set.filter(category_date__month=month,category_date__year=year))>0:
            categories = get_list_or_404(Category, category_person=person, category_date__month=month,category_date__year=year)
        else:
            categories = []
        expected,spent,left = calculate_summary(categories)
        today = datetime.datetime.today()
        current_user = get_object_or_404(People, username=request.user)
        context = {
            'categories':categories,
            'month':today.month,
            'year':today.year,
            'expected': expected,
            'spent': spent,
            'left':left,
            "current_user":current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request, "categories/index_person.html" ,context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

def index_diff_month(request,person_id,month,year):
    if request.user.is_authenticated:
        person = get_object_or_404(People, id=person_id)
        if len(person.category_set.all())>=1:
            categories= get_list_or_404(Category,category_person=person,category_date__month=month,category_date__year=year)
        else:
            categories = []
        current_user = current_user = get_object_or_404(People, username=request.user)
        today = datetime.datetime.today()
        context = {
            'person':person,
            'categories':categories,
            'month':month,
            'year':year,
            "current_user":current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request, "categories/index_person.html" ,context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)
    
def addCategory(request,person_id):
    if request.user.is_authenticated:
        person = get_object_or_404(People, id=person_id)
        initial_data = {
            'category_person' : person
        }
        form = CategoryAddForm(request.POST or None,initial=initial_data,hide_condition=True)
        if request.method == "POST":
            if form.is_valid():
                form.save()
                form = CategoryAddForm(initial=initial_data,hide_condition=True)
            else:
                print("Something happend!")
                form = CategoryAddForm(initial=initial_data,hide_condition=True)
        today = datetime.datetime.today()
        current_user = current_user = get_object_or_404(People, username=request.user)
        context={
            "person":person,
            "form":form,
            'month':today.month,
            'year':today.year,
            'current_user':current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request,"categories/new_category.html",context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

def editCategory(request,person_id,category_id):
    if request.user.is_authenticated:
        person = get_object_or_404(People, id=person_id)
        category = get_object_or_404(Category, id=category_id)
        my_instance = category
        form = CategoryAddForm(request.POST or None,instance=my_instance,hide_condition=True)
        if request.method == "POST":
            if form.is_valid():
                form.save()
                form = CategoryAddForm(instance=my_instance,hide_condition=True)
            else:
                print("Failed validation")
                form = CategoryAddForm(instance=my_instance,hide_condition=True)
        today = datetime.datetime.today()
        current_user = current_user = get_object_or_404(People, username=request.user)
        context = {
            'person':person,
            'category':category,
            'form':form,
            'month':today.month,
            'year':today.year,
            'current_user':current_user
        }
        today = datetime.datetime.today()
        context["this_month"] = today.month
        context["this_year"] = today.year
        return render(request,"categories/edit_category.html",context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

def deleteCategory(request,person_id,category_id):
    if request.user.is_authenticated:
        person = get_object_or_404(People, id=person_id)
        category = get_object_or_404(Category, id=category_id)
        month = category.category_date.month
        year = category.category_date.year
        my_instance = category
        form = CategoryAddForm(request.POST or None,instance=my_instance,hide_condition=True)
        if request.method == "POST":
            if form.is_valid():
                obj = form.save(commit=False)
                obj.delete()
                return redirect(f"../../{month}_{year}")
    
        else:
            today = datetime.datetime.today()
            current_user = current_user = get_object_or_404(People, username=request.user)
            context = {
                'person':person,
                'category':category,
                'form':form,
                'month':today.month,
                'year':today.year,
                'current_user':current_user
            }
            today = datetime.datetime.today()
            context["this_month"] = today.month
            context["this_year"] = today.year
            return render(request,"categories/delete_category.html",context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

mysite/categories/templates/categories/delete_category.html
{% extends 'bases/header.html' %}

{% block content %}

<h1>Categories</h1>
<h3>Delete Category Expense {{person.person_name}}, Category : {{category.category_name}}</h3>
<form method=POST action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-outline-danger' value = "Confirm this Delete" >
</form>
<br>
<a href="{% url 'categories:person_category_index' person_id=person.id month=month year=year %}" ><button type='button' class='btn btn btn-outline-info' >Back to Expense Report</button></a>
<br><br>
{% endblock %}

mysite/categories/templates/categories/edit_category.html
{% extends 'bases/header.html' %}

{% block content %}
<br>
<h3>Edit Category Expense {{person.person_name}}, Category : {{category.category_name}}</h3>
<form method=POST action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-outline-success' value = "Save Edits!" >
</form>
<br>
<button type='button' class='btn btn-outline-info' ><a href="{% url 'categories:person_category_index' person_id=person.id month=month year=year %}" >Back to Expense Report</a></button>
<br><br>
{% endblock %}

mysite/categories/templates/categories/index.html
{% extends 'bases/header.html' %}

{% block content %}
<br>
<h2>{{person.person_name}}'s Expense Report for {{month}}/{{year}}</h2>
<br>
{% if other_members|length > 0 %}
    <h3>Partner at {{person.group_couple.group_name}} </h3>
    <ul>
        {% for peep in other_members %}
        <li>{{peep.person_name}}</li>
        {% endfor %}
    </ul>
{% endif %}

<h3>Summary</h3>
    <table>
        <thead>
            <tr>
                <th>Expected</th>
                <th>Spent</th>
                <th>Left</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{expected}}</td>
                <td>{{spent}}</td>
                <td>{{left}}</td>
            </tr>
        </tbody>
    </table>
    <br>
<h3>Categories for month:{{month}} year:{{year}}</h3>
{% if categories|length > 0 %}
    <!--Done to use custom filter subtract variable by variable -->
    {% load categories_extras %}
    <table>
        <tr>
            <th>Category Name</th>
            <th>Expected</th>
            <th>Spent</th>
            <th>Left</th>
            <th>Add Expense</th>
            <th>Detail View</th>
            <th>Delete Category</th>
        </tr>
        {% for category in categories %}
        <tr>
            <td><a href="{% url 'categories:edit_category' person_id=person.id category_id=category.id %}" >{{category.category_name}}</a></td>
            <td>{{category.category_expected}}</td>
            <td>{{category.category_spent}}</td>
            <td>{{category.category_expected|subtract:category.category_spent}}</td>
            {% if category.category_name != 'credit_card' %}
            <td><a href="{% url 'expenses:add_expense' person_id=person.id category_id=category.id   %}"><button type ='button' class = 'btn btn-sm btn-outline-success' >Add Expense</button></a></td> 
            {% else %}
            <td><a href="{% url 'expenses:add_expense' person_id=person.id category_id=category.id   %}"><button type='button' class='btn btn-sm btn-outline-success' >Make Payment</button></a></td>
            {% endif %}
            <td><a href="{% url 'expenses:category_expense_list' person_id=person.id category_id=category.id   %}"><button type = 'button' class= 'btn btn-sm btn-outline-info' >Category Details</button></a></td>
            <td><a href="{% url 'categories:delete_category' person_id=person.id category_id=category.id %}" ><button type='button' class='btn btn-sm btn-outline-danger' >Delete Category</button></a></td>
        </tr>
        {% endfor %}
    </table>
    
{% else %}
    <p>{{person.person_name}} has no expenses setup at this moment</p>
{% endif %}
<br>
<a href="{% url 'categories:new_category' person_id=person.id %}" ><button type='button' class='btn btn-outline-primary' >Add an Expense Category</button></a>
<br><br><br>
{% endblock %}

mysite/categories/templates/categories/index_person.html
{% extends 'bases/header.html' %}

{% block content %}
{% load categories_extras %}
<h3>Summary {{person.person_name}}</h3>
    <table>
        <thead>
            <tr>
                <th>Expected</th>
                <th>Spent</th>
                <th>Left</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{expected}}</td>
                <td>{{spent}}</td>
                <td>{{left}}</td>
            </tr>
        </tbody>
    </table>
    <br>

<h3>Categories {{person.person_name}}</h3>
<table>
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Owner</th>
            <th>Expected</th>
            <th>Spent</th>
            <th>Left</th>
        </tr>
    </thead>
    {% for category in categories %}
        <tr>
            <td>{{category.category_name}}</td>
            <td>{{category.category_person.person_name}}</td>
            <td>{{category.category_expected}}</td>
            <td>{{category.category_spent}}</td>
            <td>{{category.category_expected|subtract:category.category_spent}}</td>
        </tr>
    {% endfor %}
    <tbody>

    </tbody>
</table>
    <!--Done to use custom filter subtract variable by variable -->
    {% load categories_extras %}
<br>


<br><br><br>
{% endblock %}

mysite/categories/templates/categories/index_team.html
{% extends 'bases/header.html' %}

{% block content %}
{% load categories_extras %}
<h3>Summary {{group.group_name}}</h3>
    <table>
        <thead>
            <tr>
                <th>Expected</th>
                <th>Spent</th>
                <th>Left</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{expected}}</td>
                <td>{{spent}}</td>
                <td>{{left}}</td>
            </tr>
        </tbody>
    </table>
    <br>

<h3>Categories {{group.group_name}}</h3>
<table>
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Owner</th>
            <th>Expected</th>
            <th>Spent</th>
            <th>Left</th>
        </tr>
    </thead>
    {% for category in categories %}
        <tr>
            <td>{{category.category_name}}</td>
            <td>{{category.category_person.person_name}}</td>
            <td>{{category.category_expected}}</td>
            <td>{{category.category_spent}}</td>
            <td>{{category.category_expected|subtract:category.category_spent}}</td>
        </tr>
    {% endfor %}
    <tbody>

    </tbody>
</table>
    <!--Done to use custom filter subtract variable by variable -->
    {% load categories_extras %}
<br>


<br><br><br>
{% endblock %}

mysite/categories/templates/categories/new_category.html
{% extends 'bases/header.html' %}

{% block content %}
<br>
<h3>Add a new Expense Category for {{person.person_name}}</h3><br>
<form method=POST action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-outline-success' value = "Save This Expense!" >
</form>
<br>
<a href="{% url 'categories:person_category_index' person_id=person.id month=month year=year %}" ><button type='button' class='btn btn-outline-info' >Back to Expense Report</button></a>
<br><br>
{% endblock %}