mysite/bases/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'bases'
urlpatterns= [
    path("",views.landing, name='landing')
]

mysite/categories/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'categories'
urlpatterns= [
    #categories/1/
    path("<int:person_id>/<int:month>_<int:year>/",views.index, name='person_category_index'),
    #categories/1/newCategory/
    path("<int:person_id>/newCategory/",views.addCategory,name="new_category"),
    #categories/1/editCategory/2/
    path("<int:person_id>/editCategory/<int:category_id>/",views.editCategory,name="edit_category"),
    #categories/1/deleteCategory/2/
    path("<int:person_id>/deleteCategory/<int:category_id>/",views.deleteCategory,name='delete_category'),
    #categories/group/1/
    path("group/<int:group_id>/<int:month>_<int:year>/",views.index_team , name="team_category_index"),
    path("person/<int:person_id>/<int:month>_<int:year>/",views.index_person , name="person_category_index_summary"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('people/',include('people.urls')),
    path('categories/',include('categories.urls')),
    path('expenses/',include('expenses.urls')),
    path("",include('bases.urls'))

]

mysite/people/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'people'
urlpatterns= [
    #groups
    path("",views.index,name='people_index'),
    path("newperson/",views.create_person, name='create_person'),
    path("<int:my_id>/",views.edit_person, name='edit_person'),
]

mysite/people/models.py
from django.db import models
from groups.models import Group

# Create your models here.
class People(models.Model):

    def __str__(self):
        return self.person_name

    group_couple = models.ForeignKey(Group,on_delete=models.CASCADE)
    person_name= models.CharField(max_length=70)
    username = models.CharField(max_length=70,unique=True)

mysite/people/forms.py
from django import forms
from .models import People
from groups.models import Group

class PersonAddForm(forms.ModelForm):

    class Meta:
        model= People
        fields = [
            'group_couple',
            'person_name',
            'username'
        ]

mysite/people/views.py
from django.shortcuts import render, get_object_or_404,get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect

from groups.models import Group
from .models import People
from .forms import PersonAddForm

import datetime
# Create your views here.
def index(request):
    people = People.objects.all()
    current_user = current_user = get_object_or_404(People, username=request.user)
    context = {
        'people':people,
        'current_user':current_user
    }
    today = datetime.datetime.today()
    context["this_month"] = today.month
    context["this_year"] = today.year
    return render(request, "people/index.html" ,context)

def create_person(request):
    group = Group.objects.get(id=1)
    initial_data = {
        'group_couple' : group
    }
    form = PersonAddForm(request.POST or None,initial=initial_data)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            form = PersonAddForm()
        else:
            print("Something happend!")
            form = PersonAddForm()
    current_user = current_user = get_object_or_404(People, username=request.user)
    context= {
        'form':form,
        'current_user':current_user
    }
    today = datetime.datetime.today()
    context["this_month"] = today.month
    context["this_year"] = today.year
    return render(request,'people/create_person.html',context)

def edit_person(request,my_id):
    person = People.objects.get(id=my_id)
    form = PersonAddForm(request.POST or None,instance=person)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            form = PersonAddForm(instance=person)
        else:
            print("Something happend!")
            form = PersonAddForm()
    today = datetime.datetime.today()
    current_user = current_user = get_object_or_404(People, username=request.user)
    context = {
        'form':form,
        'person':person,
        'month':today.month,
        'year':today.year,
        'current_user':current_user
    }
    today = datetime.datetime.today()
    context["this_month"] = today.month
    context["this_year"] = today.year
    return render(request,'people/edit_person.html',context)

mysite/people/templates/people/create_person.html
{% extends 'bases/header.html' %}

{% block content %}
<h1>People</h1>

<form method=POST action="" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = "Add Person!" >
</form>

<h3>All set with adding?</h3>
<button><a href="{% url 'people:people_index' %}" >Back to summary</a></button>
{% endblock %}

mysite/people/templates/people/edit_person.html
{% extends 'bases/header.html' %}

{% block content %}
<h1>People</h1>
<form method=POST action="" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = "Save Edits!" >
</form>
<br>
<button><a href="{% url 'categories:person_category_index' person_id=person.id month=month year=year %}" >{{person.person_name}} Expenses</a></button>
<button><a href="{% url 'groups:inspect_group' person.group_couple.id %}" >{{person.group_couple.group_name}}</a></button>
{% endblock %}

mysite/people/templates/people/index.html
{% extends 'bases/header.html' %}

{% block content %}
<h1>People</h1>
<h3>People list</h3>
<ul>
    {% for person in people %}
    <li><a href="{{person.id}}/" >{{person.person_name}} FROM TEAM {{person.group_couple}}</a></li>
    {% endfor %}
</ul>

<button> <a href= "{% url 'people:create_person' %}">Add a new Person</a> </button>
<h3>Visit Groups?</h3>
<button><a href="{% url 'groups:groups_index' %}" >Click to visit groups</a> </button>
{% endblock %}