mysite/bases/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'bases'
urlpatterns= [
    path("",views.landing, name='landing')
]

mysite/categories/urls.py
from django.urls import path
from . import views 
#{% url 'people:people_index' %}
app_name= 'categories'
urlpatterns= [
    #categories/1/
    path("<int:person_id>/<int:month>_<int:year>/",views.index, name='person_category_index'),
    #categories/1/newCategory/
    path("<int:person_id>/newCategory/",views.addCategory,name="new_category"),
    #categories/1/editCategory/2/
    path("<int:person_id>/editCategory/<int:category_id>/",views.editCategory,name="edit_category"),
    #categories/1/deleteCategory/2/
    path("<int:person_id>/deleteCategory/<int:category_id>/",views.deleteCategory,name='delete_category'),
    #categories/group/1/
    path("group/<int:group_id>/<int:month>_<int:year>/",views.index_team , name="team_category_index"),
    path("person/<int:person_id>/<int:month>_<int:year>/",views.index_person , name="person_category_index_summary"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('people/',include('people.urls')),
    path('categories/',include('categories.urls')),
    path('expenses/',include('expenses.urls')),
    path("",include('bases.urls'))

]

mysite/bases/models.py
from django.db import models

# Create your models here.

mysite/bases/views.py
from django.shortcuts import render,redirect,get_object_or_404, get_list_or_404
from django.http import HttpResponse,HttpResponseRedirect

from people.models import People
from groups.models import Group 
import datetime
# Create your views here.

def landing(request):
    print(request.user)
    if request.user.is_authenticated:
        today = datetime.date.today()
        current_user = get_object_or_404(People,username=request.user)
        context = {
            'this_month':today.month,
            'this_year':today.year,
            'current_user':current_user
        }
        return render(request,'bases/landing_page.html',context)
    else:
        context = {} 
        return render(request,'bases/landing_request_login.html',context)

mysite/bases/templates/bases/header.html
<!DOCTYPE HTML>
<html lang = "en">
<head>
    <!-- basic.html -->
    <title>Finance and Budgetting app</title>
    <meta charset = "UTF-8" name="viewport" content="width-device-width , initial-scale=1"  />

    <!--bootstrap stuff -->
    {% load staticfiles %}
    <link rel='stylesheet' href="{% static 'bases/css/bootstrap.min.css' %}" type ='text/css'/ >
    <script src="{% static 'bases/js/bootstrap.min.js' %}" type="text/js" ></script>
    
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'bases:landing' %}"> Track Our Expense</a>
  <!--Think about what links I should have here -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'categories:person_category_index_summary' current_user.id this_month this_year %}">{{current_user.person_name}}<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'categories:team_category_index' current_user.group_couple.id this_month this_year %}">{{current_user.group_couple.group_name}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'categories:person_category_index' current_user.id this_month this_year  %}">My Month</a>
      </li>
    </ul>
  </div>
</nav>
    {% block content %}
    {% endblock %}
</body>

</html>

mysite/bases/templates/bases/landing_page.html
{% extends 'bases/header.html' %}

{% block content %}
<h3>Welcome back {{current_user.person_name}}</h3>
<p>Let's Visit {{month}}/{{year}} Expenses</p>
<a href= "{% url 'categories:person_category_index' current_user.id this_month this_year  %}"  > <button type='button' class='btn btn btn-outline-info'>Expense Details</button></a>
<a href="{% url 'logout' %}" ><button type='button' class = 'btn btn-outline-danger'  >Logout</button></a>
{% endblock %}

mysite/bases/templates/bases/landing_request_login.html
<!DOCTYPE HTML>
<html lang = "en">
<head>
    <!-- basic.html -->
    <title>Finance and Budgetting app</title>
    <meta charset = "UTF-8" name="viewport" content="width-device-width , initial-scale=1"  />

    <!--bootstrap stuff -->
    {% load staticfiles %}
    <link rel='stylesheet' href="{% static 'bases/css/bootstrap.min.css' %}" type ='text/css'/ >
    <script src="{% static 'bases/js/bootstrap.min.js' %}" type="text/js" ></script>
    
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>
<h1>Welcome to Track Our Expense</h1>
<h3>The Family budgetting App</h3>
<br><br>
<a href="{% url 'login' %}" ><button type='button' class = 'btn btn-outline-success' >Login</button></a>
</body>
</html>